# Publish the staging / latest / versioned CDN artifacts to Cloud Object Storage
name: Publish ai-chat-components CDN artifacts

# This workflow is triggered from the `create-release-tag-and-pr` workflow when a new tag is created
# Or can be manually triggered with tag provided
on:
  workflow_dispatch:
    inputs:
      tag:
        # Recently published version
        required: true
        description: "release tag (ie. v1.1.0-rc.0 or v1.1.0)"
        type: string
        default: "v1.1.0-rc.0"
  repository_dispatch:
    types: [publish-cdn-artifacts]

jobs:
  publish-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: "0"
          ref: ${{ github.event.client_payload.branch }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          npm run build
      - name: Build Storybook
        run: |
          cd packages/ai-chat-components
          npm run storybook:build
          npm run storybook:react:build
      - name: Check release type
        if: contains(github.event.client_payload.tag, '-rc.') || contains(github.event.inputs.tag, '-rc.')
        run: echo "PRE_RELEASE=true" >> $GITHUB_ENV
      - name: Get version of web components from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/ai-chat-components

      # If tag is a release candidate, upload the CDN artifacts to the `next` tag folder
      # ie. chat.carbondesignsystem.com/components/tag/next/breadcrumb.min.js
      - name: Upload components to COS under the `next` folder
        if: ${{ env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/dist"
          DEST_DIR: "components/tag/next"

      # If tag is a release candidate, upload the ai-chat-components Storybook to `next` tag folder
      # ie. chat.carbondesignsystem.com/components/storybook/tag/next/index.html
      - name: Upload ai-chat-components Storybook to COS under the `next` folder
        if: ${{ env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-static"
          DEST_DIR: "components/storybook/tag/next"


      # If tag is a release candidate, upload the ai-chat-components React Storybook to `next` tag folder
      # ie. chat.carbondesignsystem.com/components/storybook/react/tag/next/index.html
      - name: Upload ai-chat-components React Storybook to COS under the `next` folder
        if: ${{ env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-react-static"
          DEST_DIR: "components/storybook/react/tag/next"

      # If tag is a full release, upload the CDN artifacts to the `latest` tag folder
      # ie. chat.carbondesignsystem.com/components/tag/latest/breadcrumb.min.js
      - name: Upload components to COS under the `latest` folder
        if: ${{ !env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/dist"
          DEST_DIR: "components/tag/latest"

      # If tag is a full candidate, upload the ai-chat-components Storybook to `latest` tag folder
      # ie. chat.carbondesignsystem.com/components/storybook/tag/latest/index.html
      - name: Upload ai-chat-components Storybook to COS under the `next` folder
        if: ${{ !env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-static"
          DEST_DIR: "components/storybook/tag/latest"

      # If tag is a full candidate, upload the ai-chat-components React Storybook to `latest` tag folder
      # ie. chat.carbondesignsystem.com/components/storybook/react/tag/latest/index.html
      - name: Upload ai-chat-components React Storybook to COS under the `next` folder
        if: ${{ !env.PRE_RELEASE }}
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-react-static"
          DEST_DIR: "components/storybook/react/tag/latest"


      # Upload the CDN artifacts to versioned folder
      # ie. chat.carbondesignsystem.com/components/version/v1.x.0/breadcrumb.min.js
      - name: Upload components to COS under the versioned folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/dist"
          DEST_DIR: "components/version/v${{steps.package-version.outputs.current-version}}"

      # Upload the ai-chat-components Storybook to versioned folder
      # ie. chat.carbondesignsystem.com/components/storybook/version/v1.x.0/index.html
      - name: Upload ai-chat-components Storybook to COS under the `next` folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-static"
          DEST_DIR: "components/storybook/version/v${{steps.package-version.outputs.current-version}}"

      # Upload the ai-chat-components React Storybook to versioned folder
      # ie. chat.carbondesignsystem.com/components/storybook/react/version/v1.x.0/index.html
      - name: Upload ai-chat-components React Storybook to COS under the `next` folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat-components/storybook-react-static"
          DEST_DIR: "components/storybook/react/version/v${{steps.package-version.outputs.current-version}}"

