# This is the base release workflow dispatched by the `release-minor` or `release-patch` workflows
name: Release base
run-name: ${{ inputs.type }} - dry-run:${{ inputs.dry-run }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      semver-type:
        type: string
        default: minor
        required: true
      type:
        required: true
        type: string
        default: first rc
      dry-run:
        required: true
        description: "Run dry run?"
        type: boolean
        default: true
      force-publish:
        description: "Force publish?"
        type: boolean
        default: false

# Required for OIDC publishing https://docs.npmjs.com/trusted-publishers
permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: "0"
          token: ${{ secrets.PAT }}

      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - run: |
          git config --global user.email ${{ secrets.CARBON_BOT_EMAIL }}
          git config --global user.name ${{ secrets.CARBON_BOT_NAME }}

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org
          cache: "npm"
      - name: Install dependencies and build
        run: |
          npm install
          npx playwright install --with-deps
          npm run build
      - name: Continuous integration check
        run: npm run ci-check

      - name: Set NPM token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.CARBON_BOT_NPM_TOKEN }}" >> .npmrc

      # Set the PUBLISH environment variable to be used later in the Lerna publish command.
      # Lerna has dry run on by default, need to pass in '--yes' flag before it will go ahead and publish.
      - name: Set dry run env variable
        run: |
          if [ "${{ github.event.inputs.dry-run }}" == "false"  ]; then
            echo "PUBLISH=--yes" >> $GITHUB_ENV
          fi

      # Set the FORCE environment variable to be used later in the Lerna publish command.
      # Lerna has force-publish off by default, but is to be used in circumstances when Lerna doesn't detect changes
      # and we want to bump the version up regardless.
      # Use with dry-run set to true first to confirm the version bump before running again with dry-run set to false
      - name: Set force publish env variable
        run: |
          if [ "${{ github.event.inputs.force-publish }}" == "true"  ]; then
            echo "FORCE=--force-publish" >> $GITHUB_ENV
          fi

      - name: Publish full minor release (ie. v1.x.0)
        if: |
          github.event.inputs.type == 'full release' &&
          github.event.inputs.semver-type == 'minor'
        # pass in an empty commit so lerna will graduate the version to stable
        # even though there are no new changes from last rc
        run: |
          git commit --allow-empty -m "chore(release): graduate prerelease to stable"
          npx lerna publish minor --conventional-graduate ${{ env.PUBLISH }} ${{ env.FORCE }}

      - name: Publish first minor RC (ie. v1.x.0-rc.0)
        if: |
          github.event.inputs.type == 'first rc' &&
          github.event.inputs.semver-type == 'minor'
        run: |
          npx lerna publish preminor --conventional-prerelease --preid rc --pre-dist-tag next ${{ env.PUBLISH }} ${{ env.FORCE }}

      - name: Publish full patch release (ie. v1.0.x)
        if: |
          github.event.inputs.type == 'full release' &&
          github.event.inputs.semver-type == 'patch'
        # pass in an empty commit so lerna will graduate the version to stable
        # even though there are no new changes from last rc
        run: |
          git commit --allow-empty -m "chore(release): graduate prerelease to stable"
          npx lerna publish patch --conventional-graduate ${{ env.PUBLISH }} ${{ env.FORCE }}

      - name: Publish first patch RC (ie. v1.0.x-rc.0)
        if: |
          github.event.inputs.type == 'first rc' &&
          github.event.inputs.semver-type == 'patch'
        run: |
          npx lerna publish prepatch --conventional-prerelease --preid rc --pre-dist-tag next ${{ env.PUBLISH }} ${{ env.FORCE }}

      - name: Publish subsequent RC (ie. v1.0.0-rc.x)
        if: github.event.inputs.type == 'subsequent rc'
        run: |
          npx lerna publish prerelease --conventional-prerelease --preid rc --pre-dist-tag next ${{ env.PUBLISH }} ${{ env.FORCE }}

  # This job dispatches workflow to update the versions.js file with the latest stable version
  # and pushes the updated versions.js file up to COS.
  # This versions.js file is used to populate the version dropdown in our demo and documentation websites.
  update-versions-file:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: release
    steps:
      # Triggers only if it is a full release
      - name: Update versions.js file and upload to COS
        if: github.event.inputs.type == 'full release' && github.event.inputs.dry-run == 'false'
        uses: peter-evans/repository-dispatch@v4
        with:
          event-type: update-versions-file
          client-payload: '{"branch": "${{ github.ref_name }}"}'
